print ("Hello World")
num1 = float(input ("Digite um número: "))
num2 = float(input("Digite um segundo número: "))
num3 = float (input("Digite um terceiro número: "))
res = max(num1, num2, num3)
print (f"o maior número digitado foi: {res}")