print ("Hello World")
num1 = float(input ("Digite um número: "))
num2 = float(input("Digite um segundo número: "))
num3 = float (input("Digite um terceiro número: "))
resmax = max(num1, num2, num3)
print (f"O maior número digitado foi: {resmax}")
resmin = min(num1, num2, num3)
print (f"O menor número digitado foi: {resmin}")