print ("Hello World")
product_one = float(input("Digite o valor do produto 1: "))
product_two = float(input("Digite o valor do produto 2: "))
product_three = float(input("Digite o valor do produto 3: "))
resp = min(product_one, product_two, product_three)
print (f"O produto a ser comprado, deverá ser o de valor: {resp}")